---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Useful hack to get a local API running

Resources:
  RP:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Events:
        RP:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
